### ISSUE TITLE
An error about engine file

### ISSUE THREAD

**Issue by dustbin1415** [Yutong-gannis/Self-driving-Truck-in-Euro-Truck-Simulator2#4]
I used the `yolov6s_bdd_60.engine`  in releases to run the program, and got error:
```
[01/21/2023-01:16:43] [TRT] [W] CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage. See `CUDA_MODULE_LOADING` in https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars
[01/21/2023-01:16:44] [TRT] [E] 1: [stdArchiveReader.cpp::nvinfer1::rt::StdArchiveReader::StdArchiveReader::42] Error Code 1: Serialization (Serialization assertion stdVersionRead == serializationVersion failed.Version tag does not match. Note: Current Version: 232, Serialized Engine Version: 213)
[01/21/2023-01:16:44] [TRT] [E] 4: [runtime.cpp::nvinfer1::Runtime::deserializeCudaEngine::66] Error Code 4: Internal Error (Engine deserialization failed.)
Traceback (most recent call last):
  File "D:\autodrive\script\main.py", line 54, in <module>
    clrnet = CLRNet("D:/autodrive/Perception/LaneDetection/weights/llamas_dla34.engine")
  File "D:\autodrive/Perception\LaneDetection\clrnet_trt.py", line 75, in __init__
    self.context = self.engine.create_execution_context()
AttributeError: 'NoneType' object has no attribute 'create_execution_context'
```
After that, I tried to translate onnx file into engine file use the way in readme. But I got error again:
```
PS D:\autodrive> python tools/export.py -o .\yolov6s_bdd_60.onnx -e .\yolov6s_bdd_60.engine --end2end
Namespace(onnx='.\\yolov6s_bdd_60.onnx', engine='.\\yolov6s_bdd_60.engine', precision='fp16', verbose=False, workspace=1, calib_input=None, calib_cache='./calibration.cache', calib_num_images=5000, calib_batch_size=8, end2end=True, conf_thres=0.4, iou_thres=0.5, max_det=100)
[01/21/2023-01:22:16] [TRT] [I] [MemUsageChange] Init CUDA: CPU +233, GPU +0, now: CPU 5459, GPU 437 (MiB)
[01/21/2023-01:22:20] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +131, GPU +21, now: CPU 6051, GPU 458 (MiB)
[01/21/2023-01:22:20] [TRT] [W] CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage. See `CUDA_MODULE_LOADING` in https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars
D:\autodrive\tools\export.py:109: DeprecationWarning: Use set_memory_pool_limit instead.
  self.config.max_workspace_size = workspace * (2 ** 30)
[01/21/2023-01:22:20] [TRT] [W] onnx2trt_utils.cpp:377: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
Network Description
Input 'images' with shape (1, 3, 640, 640) and dtype DataType.FLOAT
Output 'outputs' with shape (1, 8400, 15) and dtype DataType.FLOAT
D:\autodrive\tools\export.py:143: DeprecationWarning: Use network created with NetworkDefinitionCreationFlag::EXPLICIT_BATCH flag instead.
  self.builder.max_batch_size = self.batch_size
[01/21/2023-01:22:20] [TRT] [F] Validation failed: score_activation}tion missing required fields: {
C:\_src\plugin\common\plugin.cpp:41

[01/21/2023-01:22:20] [TRT] [E] Unknown exception
Traceback (most recent call last):
  File "D:\autodrive\tools\export.py", line 288, in <module>
    main(args)
  File "D:\autodrive\tools\export.py", line 248, in main
    builder.create_network(args.onnx, args.end2end, args.conf_thres, args.iou_thres, args.max_det)
  File "D:\autodrive\tools\export.py", line 191, in create_network
    layer = self.network.add_plugin_v2([boxes.get_output(0), updated_scores.get_output(0)], nms_layer)
TypeError: add_plugin_v2(): incompatible function arguments. The following argument types are supported:
    1. (self: tensorrt.tensorrt.INetworkDefinition, inputs: List[tensorrt.tensorrt.ITensor], plugin: tensorrt.tensorrt.IPluginV2) -> tensorrt.tensorrt.IPluginV2Layer

Invoked with: <tensorrt.tensorrt.INetworkDefinition object at 0x0000021DC887E170>, [<tensorrt.tensorrt.ITensor object at 0x0000021DC87DF230>, <tensorrt.tensorrt.ITensor object at 0x0000021DC87C38B0>], None
```
How can I fix it?

**Comment by Yutong-gannis** [comment]
You have to download `yolov6s_bdd_60.onnx`, and generate your own engine file. Because the engine file  depend on your own gpu.

**Comment by ywjno** [comment]
You can use TensorRT `8.4.2.4(TensorRT 8.4 GA Update 1)` to fixed it. `TensorRT-8.5.2.2` hasn't supported.

**Comment by dustbin1415** [comment]
> You can use TensorRT `8.4.2.4(TensorRT 8.4 GA Update 1)` to fixed it. `TensorRT-8.5.x` hasn't supported.

It works, thank you. :)
